### ISSUE TITLE
Kubernetes: Use ConfigMaps to pass configs to service

### ISSUE THREAD

**Issue by tillknuesting** [net-reply-future-networks/grpc-microserv-tut#14]
https://kubernetes.io/docs/concepts/configuration/configmap/

**Comment by tach200** [comment]
using config maps to pass ports to env variables
not the most useful example but this was just to practice
https://github.com/net-reply-future-networks/grpc-microserv-tut/commit/9fb883cb04e38b698ca3ee011e07dbbfa431b76c
