### ISSUE TITLE
RESTful HTTP API proxy with gRPC-Gateway

### ISSUE THREAD

**Issue by tillknuesting** [net-reply-future-networks/grpc-microserv-tut#2]
"The gRPC-Gateway is a plugin of the Google protocol buffers compiler protoc. It reads protobuf service definitions and generates a reverse-proxy server which translates a RESTful HTTP API into gRPC. This server is generated according to the google.api.http annotations in your service definitions.

This helps you provide your APIs in both gRPC and RESTful style at the same time."

https://github.com/grpc-ecosystem/grpc-gateway

Use https://pkg.go.dev/golang.org/x/sync/errgroup to manage multiple servers that run in goutiness

**Comment by tach200** [comment]
was curious to see if how gRPC gateway would handle a rest for stream.
Simple answer is, it does't.
I have added gRPC gateway, will extend functionality of the code so can actually make use of this.
https://github.com/net-reply-future-networks/grpc-microserv-tut/commit/15687c9bcab89e2d83d5048a9be025b4d6aa9ece
